version: "3"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    container_name: app
    volumes:
      - ./app:/usr/src/app
    environment:
      FLASK_ENV: "development"
    restart: always

